// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MivexBlagajna.DataAccess;

#nullable disable

namespace MivexBlagajna.DataAccess.Migrations
{
    [DbContext(typeof(MivexBlagajnaDbContext))]
    [Migration("20221124085005_Modified_Configuration")]
    partial class Modified_Configuration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence<int>("Sifre");

            modelBuilder.Entity("MivexBlagajna.Data.Models.Komitent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FizickoLice")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmbg")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("KontaktOsoba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaticniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MestoTroska_Id")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Naziv2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Obrisano")
                        .HasColumnType("bit");

                    b.Property<string>("Pib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("PravnoLice")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sifra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR Sifre");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MestoTroska_Id");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("Komitent", (string)null);
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.Konto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Konto", (string)null);
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.MestoTroska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("NadredjenoMesto_Id")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Obrisano")
                        .HasColumnType("bit");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NadredjenoMesto_Id");

                    b.ToTable("MestaTroska", (string)null);
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.Transakcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Isplata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<int?>("Komitent_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Konto_Id")
                        .HasColumnType("int");

                    b.Property<int?>("MestoTroska_Id")
                        .HasColumnType("int");

                    b.Property<string>("Nalog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Uplata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<int?>("VrsteNaloga_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Komitent_Id");

                    b.HasIndex("Konto_Id");

                    b.HasIndex("MestoTroska_Id");

                    b.HasIndex("VrsteNaloga_Id");

                    b.ToTable("Transakcije", (string)null);
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.VrsteNaloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("VrstaNaloga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VrsteNaloga", (string)null);
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.Komitent", b =>
                {
                    b.HasOne("MivexBlagajna.Data.Models.MestoTroska", "MestoTroska")
                        .WithMany("Komitenti")
                        .HasForeignKey("MestoTroska_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MestoTroska");
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.MestoTroska", b =>
                {
                    b.HasOne("MivexBlagajna.Data.Models.MestoTroska", "RoditeljMestoTroska")
                        .WithMany("DecaMestoTroska")
                        .HasForeignKey("NadredjenoMesto_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RoditeljMestoTroska");
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.Transakcija", b =>
                {
                    b.HasOne("MivexBlagajna.Data.Models.Komitent", "Komitent")
                        .WithMany("Transakcije")
                        .HasForeignKey("Komitent_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MivexBlagajna.Data.Models.Konto", "Konto")
                        .WithMany("Transakcije")
                        .HasForeignKey("Konto_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MivexBlagajna.Data.Models.MestoTroska", "MestoTroska")
                        .WithMany("Transakcije")
                        .HasForeignKey("MestoTroska_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MivexBlagajna.Data.Models.VrsteNaloga", "VrstaNaloga")
                        .WithMany("Transakcije")
                        .HasForeignKey("VrsteNaloga_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Komitent");

                    b.Navigation("Konto");

                    b.Navigation("MestoTroska");

                    b.Navigation("VrstaNaloga");
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.Komitent", b =>
                {
                    b.Navigation("Transakcije");
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.Konto", b =>
                {
                    b.Navigation("Transakcije");
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.MestoTroska", b =>
                {
                    b.Navigation("DecaMestoTroska");

                    b.Navigation("Komitenti");

                    b.Navigation("Transakcije");
                });

            modelBuilder.Entity("MivexBlagajna.Data.Models.VrsteNaloga", b =>
                {
                    b.Navigation("Transakcije");
                });
#pragma warning restore 612, 618
        }
    }
}
