// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MivexBlagajna.DataAccess;

#nullable disable

namespace MivexBlagajna.DataAccess.Migrations
{
    [DbContext(typeof(MivexBlagajnaDbContext))]
    partial class MivexBlagajnaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MivexBlagajna.Data.Models.Komitent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FizickoLice")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktOsoba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PravnoLice")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sifra")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Komitenti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Bulevar Oslobodilaca Cacka 105b",
                            FizickoLice = false,
                            Mesto = "Cacak",
                            Naziv = "Mivex",
                            Naziv2 = "Mivex DOO",
                            PostanskiBroj = "32000",
                            PravnoLice = true,
                            Sifra = 1
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Trbusani bb",
                            FizickoLice = true,
                            Ime = "Milos",
                            Mesto = "Trbusani",
                            PostanskiBroj = "32205",
                            PravnoLice = false,
                            Prezime = "Acimovic",
                            Sifra = 2,
                            Telefon = "064/040-8769"
                        },
                        new
                        {
                            Id = 3,
                            Adresa = "Bulevar Oslobodilaca Cacka 105b",
                            FizickoLice = true,
                            Ime = "Ivan",
                            Mesto = "Cacak",
                            PostanskiBroj = "32000",
                            PravnoLice = false,
                            Prezime = "Cvorovic",
                            Sifra = 3,
                            Telefon = "064/828-1500"
                        },
                        new
                        {
                            Id = 4,
                            Adresa = "Ljubic",
                            FizickoLice = false,
                            Mesto = "Cacak",
                            Naziv = "Maloprodaja Ljubic",
                            Naziv2 = "Mivex Maloprodaja Ljubic",
                            PostanskiBroj = "32000",
                            PravnoLice = true,
                            Sifra = 4,
                            Telefon = "032/352-468"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
